"""add network column

Revision ID: 224d75080557
Revises: d8deb9657fbc
Create Date: 2026-07-13 13:56:33.908157

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '224d75080557'
down_revision: Union[str, Sequence[str], None] = 'd8deb9657fbc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wallets', sa.Column('network', sa.String(), nullable=False, server_default="ETH-SEPOLIA",))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wallets', 'network')
    # ### end Alembic commands ###
